### PR TITLE
Use correct application directories for debian-based distros

### LINKED ISSUE #72: Ubuntu installs `squid3` package and configuration in `squid` directories
### Cookbook version
3.0.0

### Platform Details
Ubuntu 16.04, AWS

When installing Squid using this chef cookbook on Ubuntu 16.04, the recipe installs config to the wrong location. This cookbook assumes the name of the package, and paths to all relavent directories, is "squid3". For this version of Ubuntu, `squid3` appears to be a valid package, as is `squid`, but the service is installed as `squid` and config and log directories are `squid`.

I've worked around this by overriding all of the relevant node attributes to point the right directories.

e.g.

```ruby
node.override['squid']['package'] = 'squid'
node.override['squid']['config_dir'] = '/etc/squid'
node.override['squid']['config_file'] = '/etc/squid/squid.conf'
node.override['squid']['service_name'] = 'squid'
node.override['squid']['log_dir'] = '/var/log/squid'
node.override['squid']['cache_dir'] = '/var/spool/squid'
node.override['squid']['coredump_dir'] = '/var/spool/squid'
```

### PR DESCRIPTION
**Pull request by petracvv**
### Description

This adds some logic to use the correct directories based on which versions use the squid vs the squid3 name for debian-based platforms. The rspec ubuntu tests were updated to use the correct names as well.

### Issues Resolved
Fixes #72 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

File: attributes/default.rb [hunk 1]
```diff
@@ -69,12 +69,21 @@
 case node['platform_family']
 
 when 'debian'
-  default['squid']['package'] = 'squid3'
-  default['squid']['config_dir'] = '/etc/squid3'
-  default['squid']['config_file'] = '/etc/squid3/squid.conf'
-  default['squid']['log_dir'] = '/var/log/squid3'
-  default['squid']['cache_dir'] = '/var/spool/squid3'
-  default['squid']['coredump_dir'] = '/var/spool/squid3'
+  if node['platform_version'] =~ /^8|^14/
```
Comment (tas50) [inline attributes/default.rb]: You'll want 9 in there as well

Comment (petracvv) [reply attributes/default.rb]: Just checked in a kitchen bento box. It is named `squid` in debian 9. For some reason they changed from `squid` in debian 7 to `squid3` in debian 8 then back to `squid` in debian 9.

```bash
root@default-debian-9:~# dpkg-query -L squid | grep -E 'etc|var'
/etc
/etc/init.d
/etc/init.d/squid
/etc/logrotate.d
/etc/logrotate.d/squid
/etc/resolvconf
/etc/resolvconf/update-libc.d
/etc/resolvconf/update-libc.d/squid
/etc/squid
/etc/squid/errorpage.css
/etc/squid/squid.conf
/etc/ufw
/etc/ufw/applications.d
/etc/ufw/applications.d/squid
/var
/var/log
/var/log/squid
/var/run
/var/spool
/var/spool/squid
```

**Comment by tas50** [comment]
Thanks for the quick response and for putting this together.

**Comment by petracvv** [comment]
No problem. Thanks for the quick merge!
